### ISSUE TITLE
cargo-c can't handle "virtual Cargo.toml"

### ISSUE THREAD

**Issue by dwbuiten** [lu-zero/cargo-c#75] opened 2020-05-06 14:31 UTC
e.g. av-metrics:

```
~/av-metrics$ cargo cbuild  --version
cargo-c 0.6.5
~/av-metrics$ cargo cinstall --prefix=/some/path
Error: CliError { error: Some(manifest path `/path/av-metrics/Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace), exit_code: 101 }
~/av-metrics$
```

**Comment by lu-zero** [comment] 2020-05-06 14:54
duplicate of https://github.com/lu-zero/cargo-c/issues/63

**Closed by lu-zero** 2020-05-06 14:54 UTC
Labels: enhancement
